# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e45c7bae00084e440a0c895d7df95c1727a482253d2a1256bc4b712e622069f54fbffbcf88de7fa4380cac4c491c83a49ea8f55acc5dca877f125f4acb5bd087

test:
  secret_key_base: 2fba271ef132b2c5a15eedc688aa7c9c4a218484dcef1f432c9382ee449ed9d9183c95b08e6ba6b8887720dc6adbb19cc8187f8b337eb4d1de41cbfb020aba42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
